import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "Buttonless"
opacity = 0.9
