---
- name: Install base16-shell for terminal color themes
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ lookup('env', 'HOME') }}/.config/base16-shell"

- name: Copy out dircolors
  copy:
    src: dircolors
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/dircolors"
    mode: "0444"

- name: Symlink .dircolors file
  file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/dircolors"
    dest: "{{ lookup('env', 'HOME') }}/.dircolors"
    state: link
