---

- name: Install ruby with homebrew
  homebrew:
    name: ruby
  when: setup_brew

- name: Install ruby with system package manager
  package:
    name: "{{ item }}"
    state: present
  loop:
    - ruby
    - ruby-dev
    - ruby-colorize
    - libncurses5-dev
    - libtinfo-dev
  become: True
  when: not setup_brew

- name: Install colorls
  gem:
    name: "{{ item }}"
  loop:
    - colorls
    - rainbow
    - clocale
    - filesize
