[".config/nvim"]
  type = "git-repo"
  url = "git@github.com:wrightbradley/nvim.git"
  refreshPeriod = "168h"
[".config/alacritty/themes"]
  type = "git-repo"
  url = "git@github.com:alacritty/alacritty-theme.git"
  refreshPeriod = "168h"
