[".config/nvim"]
type = "git-repo"
url = "git@github.com:wrightbradley/nvim.git"
refreshPeriod = "168h"
[".config/alacritty/themes"]
type = "git-repo"
url = "git@github.com:alacritty/alacritty-theme.git"
refreshPeriod = "168h"
[".config/bat/themes/tokyonight.nvim"]
type = "git-repo"
url = "git@github.com:folke/tokyonight.nvim.git"
clone.args = ["--depth=1", "--no-checkout", "--filter=blob:none"]
refreshPeriod = "720h"                                            # every 30 days
