---
- hosts: all
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  pre_tasks:
    - name: Git clone into ~/dotfiles if not already
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_local_destination }}"
        version: "{{ dotfiles_repo_version }}"
        accept_hostkey: yes
    - name: Backup files
      archive:
        path:
          - ~/.bashrc
          - ~/.zsh
          - ~/.config
          - ~/.oh-my-zsh
          - ~/.gitconfig
          - ~/.gitaliases
          - ~/.gitconfig.local
          - ~/.vimrc
          - ~/.screenrc
          - ~/.tmux.conf
          - ~/.aliases
        dest: "{{ dotfiles_home }}/ansible-dotfiles-backup-{{ date }}.tar.gz"
        format: gz
      loop:
  roles:
    - { role: elliotweiser.osx-command-line-tools, tags: osx-command-line-tools, when: ansible_os_family == 'Darwin' }
    - { role: linuxbrew, tags: linuxbrew, when: ansible_os_family != 'Darwin' and setup_brew, become: yes}
    - { role: geerlingguy.mac.homebrew, tags: homebrew, when: ansible_os_family == 'Darwin', become: yes}
    - role: geerlingguy.mac.mas
      when: ansible_os_family == 'Darwin' and (mas_installed_apps or mas_installed_app_ids)
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: ansible_os_family == 'Darwin' and configure_dock
      tags: ['dock']
    - { role: system, tags: system }
    - { role: aliases, tags: aliases }
    - { role: git, tags: git }
    - { role: bash, tags: bash }
    - { role: zsh, tags: zsh }
    - { role: chromebook, tags: chromebook, when: setup_chromebook }
    - { role: color_icons_fonts, tags: color_icons_fonts }
    - { role: gantsign.golang, tags: go }
    - { role: geerlingguy.pip, tags: python-pip }
    - { role: screenrc_tmux, tags: screenrc_tmux }
    - { role: vim, tags: vim }
    - { role: vscode, tags: vscode }
    - { role: kubernetes, tags: kubernetes}
    - { role: hugo, tags: hugo}
  post_tasks:
    - name: Change shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
      become: yes
      when: setup_zsh and not setup_brew
    - name: Change shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/local/bin/zsh
      become: yes
      when: setup_zsh and setup_brew

