---
dotfiles_repo: "https://github.com/the-wright-engineer/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: "~/dotfiles"
dotfiles_home: "~"

# Setup Var Flags
setup_aliases: True
setup_brew: True
setup_bash: True
setup_chromebook: False
setup_color: True
setup_fonts: True
setup_git: True
setup_icons: True
setup_system: True
setup_python: False
setup_screen: True
setup_tmux: True
setup_vim: True
setup_vscode: False
setup_zsh: True
install_ycm: False

gitauthor: the-wright-engineer
gitemail: bradley.wright.tech@gmail.com

# Configure shell rc files
linuxbrew_init_shell: false
linuxbrew_user: linuxbrew
linuxbrew_use_installer: true
linuxbrew_install_url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
linuxbrew_install_checksum: "sha256:586d9ddff4c8a3ab0c1e9ab3e26a4cb5e4453fe43970207c215d329531921527"

homebrew_installed_packages:
  - ansible
  - ansible-lint
  - ant
  - argo
  - argocd
  - aws-iam-authenticator
  - awscli
  - bash
  - bash-completion --force
  - cmake
  - colordiff
  - coreutils
  - dive
  - docker
  - dos2unix
  - eksctl
  - expect
  - faas-cli
  - fzf
  - git
  - glances
  - gnupg
  - gnutls
  - go
  - gradle
  - grpcurl
  - hadolint
  - helm
  - helm@2
  - htop
  - httrack
  - jq
  - jsonnet
  - k9s
  - krew
  - kube-ps1
  - kubectx
  - kubernetes-cli
  - kubeseal
  - kustomize
  - maven
  - mtr
  - neofetch
  - nmap
  - node
  - openjdk
  - packer
  - derailed/popeye/popeye
  - postgresql
  - pyenv
  - python@3.8
  - ripgrep
  - rsync
  - ruby
  - screen
  - skaffold
  - sqlite
  - starship
  - stern
  - terraform
  - tmux
  - tree
  - aquasecurity/trivy/trivy
  - vim
  - watch
  - wget
  - whois
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - handbrake
  - slack
  - iterm2
  - vlc
  - bitwarden
  - authy
  - visual-studio-code
