---
dotfiles_repo: "https://github.com/the-wright-engineer/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: "~/dotfiles"
dotfiles_home: "~"

gitauthor: the-wright-engineer
gitemail: bradley.wright.tech@gmail.com

