---
- name: Restart Dock
  ansible.builtin.command: killall Dock
  become: true
  when: ansible_os_family == "Darwin" # Only run on macOS

- name: Restart SystemUIServer
  ansible.builtin.command: killall SystemUIServer
  become: true
  when: ansible_os_family == "Darwin" # Only run on macOS
