---

# TODO check if vscode is installed
- name: Template out and setup VS Code
  block:
    - name: Template out VS Code settings file
      template:
        src: settings.json.j2
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/settings.json"
        mode: '0444'

    - name: Symlink VS Code settings file
      file:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/settings.json"
        dest: "{{ lookup('env', 'HOME') }}/.settings.json"
        state: link
  when: setup_vscode
