---

- name: Install Fonts without Homebrew
  block:
    # TODO install and run fc-cache
    # sudo apt-get install fontconfig -y
    # fc-cache -f -v

    - name: Create local font dir
      file:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        state: directory
        mode: '0744'

    - name: Download fonts
      get_url:
        url: "{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
      loop:
        - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf"
        - "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf"
  when: not setup_brew

- name: Use Homebrew to install fonts
  block:
    - homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install fonts on macOS with homebrew
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - font-caskaydia-cove-nerd-font
        - font-droid-sans-mono-nerd-font
        - font-fira-code-nerd-font
        - font-hack-nerd-font
  when: setup_brew
