---

- name: Setup Alias File
  block:
    - name: Template out Aliases file
      template:
        src: aliases.j2
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/aliases"
        mode: '0444'

    - name: Symlink Aliases file
      file:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/aliases"
        dest: "{{ lookup('env', 'HOME') }}/.aliases"
        state: link
  when: setup_aliases
