---

- name: Install default packages using system package manager
  package:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - bash
    - bash-completion
    - fzf
    - vim
    - git
    - zip
    - unzip
    - whois
    - tree
    - xclip
    - mtr
    - dnsutils
    - nmap
    - netcat
    - tmux
    - zsh
    - rsync
    - colordiff
    - jq
    - nodejs
  become: yes
  become_user: root
  when: not setup_brew and ansible_os_family != 'Darwin'

- name: Install default packages with brew
  block:
    - name: Install default taps
      command: "{{ homebrew_install_path }}/bin/brew install {{ item }}"
      loop: "{{ homebrew_installed_packages }}"
  when: setup_brew and ansible_os_family != 'Darwin'
  ignore_errors: True

- name: Install Starship Terminal
  unarchive:
    src: https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes
  when: not setup_brew
