---
- name: Force update brew after installation.
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)

- name: Test 1
  shell: test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"

- name: Test 2
  shell: test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

- name: Test 3
  shell: test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.bash_profile

- name: Test 4
  shell: echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.profile