git:
  commit:
    signOff: true
  overrideGpg: true
os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
customCommands:
  - key: "<c-g>"
    command: "unset GITHUB_TOKEN; gh pr create --fill --assignee @me {{.Form.DRAFT}} {{.Form.DEVOPS}} {{.Form.SRE}}"
    context: "global"
    loadingText: "Creating pull request on GitHub"
    prompts:
      - type: "menu"
        title: "Open a Draft PR?"
        key: "DRAFT"
        options:
          - value: ""
            name: "No"
            description: "Do not open a Draft PR"
          - value: "--draft"
            name: "Yes"
            description: "Open a Draft PR"
      - type: "menu"
        title: "Add DevOps Reviewers?"
        key: "DEVOPS"
        options:
          - value: ""
            name: "No"
            description: "Do not add DevOps as a Reviewer"
          - value: "--reviewer tackle-io/devops"
            name: "Yes"
            description: "Add DevOps as a Reviewer"
      - type: "menu"
        title: "Add SRE Reviewers?"
        key: "SRE"
        options:
          - value: ""
            name: "No"
            description: "Do not add SRE as a Reviewer"
          - value: "--reviewer tackle-io/sre"
            name: "Yes"
            description: "Add SRE as a Reviewer"
  #   command: "git remote prune {{.SelectedRemote.Name}}"
  #   context: "remotes"
  #   loadingText: "Pruning..."
  #   description: "prune deleted remote branches"
  - key: "b"
    command: "git branch --merged master | grep -v '^[ *]*master$' | xargs git branch -d"
    context: "localBranches"
    loadingText: "Pruning..."
    description: "prune local branches that have been merged to master"
  - key: "C"
    command: "git cz -S"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "P"
    command: "git push --set-upstream origin '$(git-branch-current 2>/dev/null)'"
    context: "localBranches"
    loadingText: "Pushing..."
    description: "Push changes to upstream origin"
