---

# TODO ensure zsh is installed, ensure oh-my-zsh is installed, template out config files
- name: Setup ZSH and Oh-my-Zsh
  block:
    - name: Install oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

    - name: Install zsh plugins
      git:
        repo: "{{ item.repo }}"
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/{{ item.dir }}"
      loop:
        - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", dir: "zsh-syntax-highlighting" }
        - { repo: "https://github.com/zsh-users/zsh-autosuggestions", dir: "zsh-autosuggestions" }
        - { repo: "https://github.com/zsh-users/zsh-completions", dir: "zsh-completions" }
        - { repo: "https://github.com/agkozak/zsh-z", dir: "zsh-z" }

    - name: Template out .zshrc file
      template:
        src: zshrc.j2
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/zshrc"
        mode: '0444'

    - name: Symlink .zshrc file
      file:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/zshrc"
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        state: link

    - name: Create a config directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.config"
        state: directory
        mode: '0755'

    - name: Copy over starship file
      copy:
        src: starship
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/starship.toml"
        mode: '0444'

    - name: Symlink starship file
      file:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/starship.toml"
        dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"
        state: link

  when: setup_zsh
