---
# Setup Var Flags
setup_aliases: true
setup_brew: true
setup_bash: true
setup_color: true
setup_fonts: true
setup_git: true
setup_icons: true
setup_system: true
setup_python: false
setup_tmux: true
setup_vim: true
setup_vscode: true
setup_zsh: true
setup_starship: true
setup_nvim: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - "App Store"
  - "System Preferences"
  - Calendar
  - Contacts
  - FaceTime
  - Freeform
  - Launchpad
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - TV
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "Alacritty"
    path: "/Applications/Alacritty.app/"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 3
  - name: "Mail"
    path: "/Applications/Mail.app/"
    pos: 4

homebrew_installed_packages:
  - agg
  - ankitpokhrel/jira-cli/jira-cli
  - ansible
  - ansible-lint
  - ant
  - aquasecurity/trivy/trivy
  - argo
  - argocd
  - asciinema
  - asdf
  - asitop
  - autoconf-archive
  - autogen
  - automake
  - aws-iam-authenticator
  - aws/tap/ec2-instance-selector
  - aws/tap/eks-node-viewer
  - awscli
  - bash
  - bash-completion
  - bitwarden-cli
  - bzip2
  - cdk8s
  - charmbracelet/tap/freeze
  - chart-testing
  - checkov
  - chezmoi
  - cirruslabs/cli/tart
  - cli53
  - cmctl
  - codespell
  - colima
  - colordiff
  - container-diff
  - cookiecutter
  - coreutils
  - cue
  - curl
  - cypher-shell
  - derailed/popeye/popeye
  - detect-secrets
  - direnv
  - dive
  - { name: docker, install_options: "formula" }
  - docker-credential-helper
  - docker-credential-helper-ecr
  - docker-slim
  - dockutil
  - dos2unix
  - eksctl
  - entr
  - eslint
  - expect
  - eza
  - faas-cli
  - fairwindsops/tap/nova
  - fairwindsops/tap/polaris
  - fd
  - ffmpeg
  - flake8
  - fzf
  - gh
  - gifsicle
  - gifski
  - git
  - git-cliff
  - git-xargs
  - glances
  - glow
  - gnu-sed
  - gnupg
  - gnutls
  - go
  - go-jsonnet
  - goreleaser/tap/goreleaser
  - gradle
  - grafana
  - grafana-agent
  - grep
  - grpcurl
  - gstreamer
  - hadolint
  - helm
  - { name: hey, install_options: "formula" }
  - hidapi
  - hopenpgp-tools
  - htop
  - httrack
  - iperf3
  - jdupes
  - jinja2-cli
  - jq
  - jsonnet-bundler
  - k2tf
  - k3d
  - k3sup
  - k9s
  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai
  - krew
  - kube-linter
  - kube-ps1
  - kubeconform
  - kubectx
  - kubernetes-cli
  - kubescape/tap/kubescape-cli
  - kubeseal
  - kustomize
  - kwok
  - lazygit
  - libfido2
  - libpq
  - lindell/multi-gitter/multi-gitter
  - logcli
  - luarocks
  - make
  - mas
  - maven
  - mike-engel/jwt-cli/jwt-cli
  - mimirtool
  - minikube
  - mosh
  - mtr
  - mysql-client
  - ncurses
  - neofetch
  - neomutt
  - neovim
  - nmap
  - node
  - norwoodj/tap/helm-docs
  - nvm
  - openjdk
  - openssh
  - openssl@3
  - ossp-uuid
  - osx-cpu-temp
  - oven-sh/bun/bun
  - packer
  - pandoc
  - parallel
  - pdm
  - perl
  - pgcli
  - pinentry-mac
  - pipenv
  - pngpaste
  - poetry
  - popeye
  - postgresql@14
  - pre-commit
  - prettier
  - proselint
  - pwgen
  - pyenv
  - pyenv-virtualenv
  - pyyaml
  - readline
  - rename
  - ripgrep
  - rsync
  - ruby
  - rust
  - rye
  - screen
  - shellcheck
  - shfmt
  - skaffold
  - skopeo
  - socat
  - { name: spark, install_options: "formula" }
  - sqlite
  - starship
  - stern
  - stylua
  - tcl-tk
  - terraform
  - terraform-docs
  - terragrunt
  - terrascan
  - tflint
  - tfsec
  - theden/gcopy/gcopy
  - tilt-dev/tap/tilt
  - tmux
  - tree
  - trippy
  - trivy
  - uv
  - vale
  - vcluster
  - veeso/termscp/termscp
  - velero
  - vhs
  - vim
  - watch
  - wget
  - whois
  - wireguard-tools
  - xz
  - yamlfmt
  - yamllint
  - yapf
  - yarn
  - ykman
  - ykpers
  - yq
  - yubikey-personalization
  - zlib
  - zoxide
  - zsh
  - zsh-vi-mode

homebrew_taps:
  - ankitpokhrel/jira-cli
  - aquasecurity/trivy
  - aws/tap
  - charmbracelet/tap
  - cirruslabs/cli
  - derailed/popeye
  - fairwindsops/tap
  - goreleaser/tap
  - koekeishiya/formulae
  - kubescape/tap
  - lindell/multi-gitter
  - mike-engel/jwt-cli
  - norwoodj/tap
  - oven-sh/bun
  - theden/gcopy
  - tilt-dev/tap
  - veeso/termscp
  - weaveworks/tap

# TODO: add yubikey, propresenter, logitech, atem mini apps
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - authy
  - backblaze
  - balenaetcher
  - bartender
  - blackhole-2ch
  - discord
  - disk-inventory-x
  - elgato-camera-hub
  - elgato-control-center
  - elgato-stream-deck
  - elgato-wave-link
  - firefox
  - font-caskaydia-cove-nerd-font
  - font-droid-sans-mono-nerd-font
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-symbols-only-nerd-font
  - google-chrome
  - google-cloud-sdk
  - handbrake
  - hiddenbar
  - iterm2
  - keycastr
  - keymapp
  - lens
  - logi-options-plus
  - obs
  - obsidian
  - rancher
  - raspberry-pi-imager
  - signal
  - slack
  - spotify
  - tailscale
  - vlc
  - visual-studio-code
  - zoom

mas_installed_apps:
  - { id: 441258766, name: "Magnet (2.6.0)" }
  - { id: 682658836, name: "GarageBand (10.4.4)" }
  - { id: 1352778147, name: "Bitwarden (1.29.1)" }
  - { id: 1319778037, name: "iStat Menus (6.60)" }
  # - { id: 966085870, name: "TickTick (4.0.21)" }
  # - { id: 1451685025, name: "WireGuard (1.0.15)" }
  # - { id: 1090488118, name: "Gemini 2 (2.8.11)" }
  # - { id: 1176895641, name: "Spark (2.11.6)" }
  # - { id: 446243721, name: "Disk Space Analyzer Free  (3.6.3)" }
