---
# Setup Var Flags
setup_aliases: true
setup_brew: true
setup_bash: true
setup_color: true
setup_fonts: true
setup_git: true
setup_icons: true
setup_system: true
setup_python: false
setup_tmux: true
setup_vim: true
setup_vscode: true
setup_zsh: true
setup_starship: true
setup_nvim: true

# Configure shell rc files
linuxbrew_init_shell: false
linuxbrew_user: linuxbrew
linuxbrew_use_installer: true
linuxbrew_install_url: 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh'
linuxbrew_install_checksum: 'sha256:586d9ddff4c8a3ab0c1e9ab3e26a4cb5e4453fe43970207c215d329531921527'
