---

# TODO check for git package
- name: Setup gitconfig and completion
  block:
    - name: Template out gitconfig.local file
      template:
        src: gitconfig.local.j2
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/gitconfig.local"
        mode: '0444'

    - name: Copy various git files
      copy:
        src: "{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/{{ item }}"
        mode: '0444'
      loop:
        - gitconfig
        - gitignore

    - name: Symlink various git config files
      file:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/.{{ item }}"
        state: link
        force: yes
      loop:
        - gitconfig
        - gitconfig.local
        - gitignore

    - name: Download git completion
      get_url:
        url: "{{ item.name }}"
        dest: "{{ lookup('env', 'HOME') }}/.{{ item.location }}"
      loop:
        - { name: "https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh", location: "git-completion.zsh" }
        - { name: "https://github.com/git/git/blob/master/contrib/completion/git-completion.bash", location: "git-completion.bash" }
  when: setup_git
