---

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
    state: directory
    mode: '0755'

- name: Setup Alias File
  block:
    - name: Template out Aliases file
      template:
        src: aliases.j2
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles/aliases"
        mode: '0444'

    - name: Symlink Aliases file
      file:
        src: "{{ lookup('env', 'HOME') }}/.dotfiles/aliases"
        dest: "{{ lookup('env', 'HOME') }}/.aliases"
        state: link
  when: setup_aliases
