# vim:ft=yaml.ansible
- name: Dotfile Bootstrap
  hosts: all
  roles:
    - role: geerlingguy.mac.homebrew
      when: ansible_os_family == 'Darwin'
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when: ansible_os_family == 'Darwin' and (mas_installed_apps or mas_installed_app_ids)
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: ansible_os_family == 'Darwin' and configure_dock
      tags: ["dock"]
    # - {role: packages, tags: packages}
    - {role: personal, tags: personal}
  post_tasks:
    - name: Change shell
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
      become: true
      when: setup_zsh and not setup_brew
    - name: Change shell
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/local/bin/zsh
      become: true
      when: setup_zsh and setup_brew and ansible_architecture != "arm64"
    - name: Change shell
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /opt/homebrew/bin/zsh
      become: true
      when: setup_zsh and setup_brew and ansible_architecture == "arm64"
