---
# vim:ft=yaml.ansible
- name: Dotfile Bootstrap
  hosts: all
  pre_tasks:
    - name: Set host facts for Homebrew and MAS apps
      ansible.builtin.set_fact:
        homebrew_taps: '{{ (homebrew_taps | default([])) + (personal_homebrew_taps | default([])) + (work_homebrew_taps | default([])) }}'
        homebrew_cask_apps: '{{ (homebrew_cask_apps | default([])) + (personal_homebrew_cask_apps | default([])) + (work_homebrew_cask_apps | default([])) }}'
        mas_installed_apps: '{{ (mas_installed_apps | default([])) + (personal_mas_installed_apps | default([])) + (work_mas_installed_apps | default([])) }}'
        homebrew_installed_packages: '{{ (homebrew_installed_packages | default([])) + (personal_homebrew_installed_packages | default([])) + (work_homebrew_installed_packages | default([])) }}'
  roles:
    - role: geerlingguy.mac.homebrew
      when: ansible_os_family == 'Darwin'
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: ansible_os_family == 'Darwin' and (mas_installed_apps or mas_installed_app_ids)
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: ansible_os_family == 'Darwin' and configure_dock
      tags: ['dock']
    - role: personal
      tags: personal
  post_tasks:
    - name: Determine shell based on architecture and brew setup
      ansible.builtin.set_fact:
        zsh_shell: >-
          {%- if ansible_architecture == "arm64" and setup_brew -%} /opt/homebrew/bin/zsh {%- elif setup_brew -%} /usr/local/bin/zsh {%- else -%} /bin/zsh {%- endif -%}
    - name: Change shell to Zsh
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: '{{ zsh_shell }}'
      become: true
      when: setup_zsh
