prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    type: null
  - title: Needs My Review
    filters: is:open review-requested:@me
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
    - key: c
      command: |
        tmux new-window -c {{.RepoPath}}.git/main '
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":DiffviewOpen main...{{.HeadRefName}}"
        '
repoPaths:
  :owner/:repo: ~/Projects/code/github.com/:owner/:repo # template if you always clone github repos in a consistent location
  # wrightbradley/*: ~/code/repos/wrightbradley/* # will match dlvhdr/repo-name to ~/code/repos/dlvhdr/repo-name
  # wrightbradley/gh-dash: ~/code/gh-dash # will not match wildcard and map to specified path
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: delta
confirmQuit: false
