"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:blue fg:surface0)\
$kubernetes\
[](bg:orange fg:blue)\
$aws\
[](bg:purple fg:orange)\
$directory\
[](bg:green fg:purple)\
$git_branch\
$git_status\
[ ](fg:green)\
$line_break$character"""

palette = 'tokyo_night'

# # Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 10
#
# # Timeout for commands executed by starship (in milliseconds).
# command_timeout = 200

# Disable the blank line at the start of the prompt
add_newline = false

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.tokyo_night]
rosewater = "#c0caf5" # Lighter blue for a soft accent
flamingo = "#f7768e" # Bright pink/red
pink = "#bb9af7" # Purple, as Tokyo Night uses various shades of purple
orange = "#ff9e64" # Brighter orange for contrast
red = "#f7768e" # Tokyo Night's red
maroon = "#7aa2f7" # Blue as a substitute for maroon
peach = "#ff9e64" # Reusing the brighter orange for peach
yellow = "#e0af68" # Yellow with a bit of an orange tint
green = "#9ece6a" # Vibrant green
teal = "#1abc9c" # A teal/cyan color
sky = "#7aa2f7" # Blue for the sky
sapphire = "#7aa2f7" # Another shade of blue for sapphire
blue = "#7aa2f7" # Tokyo Night's signature blue
lavender = "#bb9af7" # Purple, similar to pink but more subdued
text = "#c0caf5" # Light blue for text
subtext1 = "#a9b1d6" # Subdued blue for subtext
subtext0 = "#9aa5ce" # Even more subdued blue
overlay2 = "#414868" # Dark blue for overlays
overlay1 = "#3b4261" # Darker blue for overlays
overlay0 = "#333a4d" # Even darker blue
surface2 = "#2a2e3e" # Dark surface color
surface1 = "#24283b" # Darker surface color
surface0 = "#1f2335" # Darkest surface color, close to the base
base = "#1a1b26" # Base color of Tokyo Night, very dark blue
mantle = "#16161e" # Slightly lighter than base
crust = "#131419" # Slightly darker than base, for the crust

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[aws]
format = '[$symbol\[$profile\($region\)\]]($style)'
style = "fg:mantle bg:orange"
symbol = " "

[aws.region_aliases]
us-east-1 = "VA"
us-west-2 = "OR"

[kubernetes]
symbol = '⎈ '
style = "fg:mantle bg:blue"
disabled = false
format = '[$symbol$context \($namespace\)]($style)'

[terraform]
format = 'via [$symbol$workspace]($style) '
symbol = '󱁢'
style = 'bold 105'
disabled = false
detect_extensions = [
    'tf',
    'hcl',
]
detect_files = []
detect_folders = ['.terraform']

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
disabled = true
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
disabled = true
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
disabled = true
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
disabled = true
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[✗](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
