---
- name: Git clone GitHub Repos
  git:
    # TODO: handle SSH and HTTPS gracefully
    # repo: 'git@github.com:{{ item }}.git'
    repo: 'https://github.com/{{ item }}.git'
    dest: '~/Projects/code/github.com/{{ item }}'
    version: HEAD
    accept_hostkey: true
  loop:
    - wrightbradley/dotfiles
    - wrightbradley/nvim
